//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ARcBridgeInput.rc
//
#define ID_ALL_FIXFREE                  3
#define ID_BUTTON_ADDLOAD               3
#define ID_BUTTON_REMOVELOAD            4
#define IDD_DIALOG_EXPJOINT_REF         1046
#define IDC_RECOMMOND                   1101
#define IDC_BUTTON_RECOMMAND            1102
#define IDC_BUTTON_PREV                 1103
#define IDC_BUTTON_NEXT                 1104
#define IDC_BUTTON_APPLY                1105
#define IDC_BUTTON_EXAMINE              1106
#define IDC_BUTTON_SELECTSHOEFIX        1107
#define IDC_BUTTON_EXAMINE2             1107
#define IDC_BUTTON_CORNER               1107
#define IDC_BUTTON_ADD_COMBINE          1108
#define IDC_BUTTON_RECOMMAND_ALL        1109
#define IDC_BUTTON_APPLY_MIRROR         1110
#define IDC_GRID                        1111
#define IDC_BUTTON_SODAN                1112
#define IDC_BUTTON_ADD_REBAR            1112
#define IDC_BUTTON_REBARJOINT           1113
#define IDC_BUTTON_RECOMMAND_ALL3       1113
#define IDC_BUTTON_REMOVE_REBAR         1113
#define IDC_BUTTON_SAMEAPPLY            1114
#define IDC_BUTTON_STRUP                1115
#define IDC_BUTTON_SAMESTTEND           1116
#define IDC_BUTTON_REMOVE_COMBINE       1117
#define IDC_GRID_RAIL                   1118
#define IDC_BUTTON_ADDRATE              1119
#define IDC_GRID_VERT                   1120
#define IDC_BUTTON_REBARDAN             1121
#define IDC_BUTTON_ROUND                1122
#define IDC_BUTTON_SAMEINWALL           1123
#define IDC_BUTTON_APPLY_MIRROR2        1124
#define IDC_GRID_SHEAR                  1125
#define IDC_GRID_POS                    1126
#define IDC_BUTTON_REBARHUNCH           1127
#define IDC_BUTTON_TYPECYCLE3           1128
#define IDC_BUTTON_APPLY_SAMEALL        1129
#define IDC_BUTTON_REBARDANBU           1130
#define IDC_BUTTON_SAMESTTEND2          1131
#define IDC_GRID_SECTION                1132
#define IDC_BUTTON_SAMEINWALL2          1133
#define IDC_BUTTON_OPTIMIZE             1134
#define IDC_BUTTON_CHECKRIB             1135
#define IDC_PROGRESS                    1136
#define IDC_HGPROGRESS                  1137
#define IDD_DIALOG_SKEYOPTION           1140
#define IDD_DIALOG_SKEWOPTION           1141
#define IDB_BITMAP_DONGBARI1            1142
#define IDD_DIALOG_BASEFACT             1143
#define IDD_DIALOG_BASEDESIGNFACT       1144
#define IDD_DIALOG_FINITE_PILE          1145
#define IDB_BITMAP_FINITE_PILE          1146
#define IDC_COMBO_LOADCOMBO             1148
#define IDC_COMBO_LOADTYPE              1149
#define IDC_COMBO_LOADCASE              1150
#define IDC_RADIO1                      1151
#define IDC_RADIO9                      1152
#define IDC_RADIO_MID                   1153
#define IDC_RADIO45                     1154
#define IDC_RADIO4                      1154
#define IDC_RADIO46                     1156
#define IDC_RADIO2                      1157
#define IDC_RADIO47                     1158
#define IDC_RADIO10                     1159
#define IDC_RADIO11                     1160
#define IDC_RADIO12                     1161
#define IDC_RADIO_AXIAL                 1162
#define IDC_RADIO13                     1163
#define IDC_RADIO14                     1164
#define IDC_RADIO15                     1165
#define IDC_RADIO_V33                   1166
#define IDC_RADIO16                     1167
#define IDC_RADIO17                     1168
#define IDC_RADIO18                     1169
#define IDC_RADIO_M22                   1170
#define IDC_RADIO19                     1171
#define IDC_RADIO20                     1172
#define IDC_RADIO21                     1173
#define IDC_RADIO_TORTION               1174
#define IDC_RADIO22                     1175
#define IDC_RADIO23                     1176
#define IDC_RADIO_DISP                  1177
#define IDC_RADIO24                     1178
#define IDC_RADIO25                     1179
#define IDC_RADIO26                     1180
#define IDC_RADIO_REACTION              1181
#define IDC_RADIO27                     1182
#define IDC_RADIO28                     1183
#define IDC_CHECK_JOINT                 1184
#define IDC_RADIO29                     1185
#define IDC_CHECK_REBAR_LENGTH          1186
#define IDC_RADIO30                     1187
#define IDC_RADIO31                     1188
#define IDC_CHECK_ELEMENT               1189
#define IDC_RADIO32                     1190
#define IDC_RADIO33                     1191
#define IDC_RADIO34                     1192
#define IDC_CHECK_RESTRAINT             1193
#define IDC_RADIO35                     1194
#define IDC_RADIO36                     1195
#define IDC_RADIO37                     1196
#define IDC_CHECK_OUTVALUE              1197
#define IDC_RADIO38                     1198
#define IDC_RADIO39                     1199
#define IDC_RADIO40                     1200
#define IDC_SLIDER_SCALE                1201
#define IDC_RADIO41                     1202
#define IDC_SLIDER_SCALE2               1203
#define IDC_RADIO42                     1204
#define IDC_RADIO43                     1205
#define IDC_RADIO44                     1206
#define IDC_EDIT_JOINTNUM_SIZE          1207
#define IDC_EDIT_ELEMENTNUM_SIZE        1208
#define IDC_CHECK_LOADTYPE              1209
#define IDC_RADIO_VIEW_YZ               1210
#define IDC_EDIT_DATASIZE               1211
#define IDC_BUTTON_BKCHANGE             1212
#define IDC_RADIO_VIEW_XZ               1213
#define IDC_BUTTON_SAVEIMG              1214
#define IDC_BUTTON_VIEW_CALC            1215
#define IDC_RADIO_VIEW_XY               1216
#define IDC_BUTTON_VIEW_SETTING         1217
#define IDC_RADIO_VIEW_3D               1218
#define IDC_EDIT6                       1219
#define IDC_EDIT2                       1220
#define IDC_EDIT3                       1221
#define IDC_EDIT4                       1222
#define IDC_EDIT5                       1223
#define IDC_COMBO_RAIL_CAR              1225
#define IDC_EDIT_EO                     1227
#define IDC_EDIT_U                      1228
#define IDC_STATIC_FACTTITLE            1229
#define IDC_EDIT_FACTVALUE              1230
#define IDC_EDIT_RD                     1231
#define IDC_BUTTON_REDRAW               1232
#define IDC_BITMAP_FINITE_PILE          1233
#define IDC_EDIT_HINGE_PHI1             1234
#define IDC_EDIT_HINGE_PHI2             1235
#define IDC_EDIT_HINGE_PHI4             1236
#define IDC_EDIT_HINGE_NOR_PHI1         1237
#define IDC_EDIT_HINGE_PHI3             1238
#define IDC_EDIT_HINGE_NOR_PHI2         1239
#define IDC_EDIT_FIX_PHI1               1240
#define IDC_EDIT_HINGE_NOR_PHI3         1241
#define IDC_EDIT_FIX_PHI2               1242
#define IDC_EDIT_FIX_PHI4               1243
#define IDC_EDIT_FIX_PHI3               1244
#define IDD_DIALOG_SELECT_SHOE          1245
#define IDC_EDIT_HINGE_NOR_PHI4         1245
#define IDC_BUTTON_ADD_LOAD             1246
#define IDC_EDIT_FIX_NOR_PHI1           1246
#define IDC_BUTTON_REMOVE_LOAD          1247
#define IDC_EDIT_FIX_NOR_PHI2           1247
#define IDC_BUTTON_BASEDATA_SAVE        1248
#define IDC_EDIT_FIX_NOR_PHI3           1248
#define IDC_BUTTON_BASEDATA_LOAD        1249
#define IDC_EDIT_UPSLAB_1DAN            1249
#define IDC_EDIT_FIX_PHI8               1249
#define IDC_EDIT_FIX_NOR_PHI4           1249
#define IDC_CHECK_ALLBRIDGE             1250
#define IDC_EDIT_UPSLAB_2DAN            1250
#define IDC_STATIC_RAIL_CAR             1251
#define IDC_EDIT_UPSLAB_3DAN            1251
#define IDC_CHECK_ALLCORNER             1251
#define IDC_CHECK_AUTO_TERMINAL         1251
#define IDC_CHECK_AUTO_CLOSE            1251
#define IDR_MENU_INPUT                  1252
#define IDC_EDIT_LOSLAB_1DAN            1252
#define IDC_CHECK_ALLCOMBO              1252
#define IDC_EDIT_LOSLAB_2DAN            1253
#define IDD_DIALOG_DEFAULT              1254
#define IDC_EDIT_LOSLAB_3DAN            1254
#define IDC_TAB_CYCLE                   1255
#define IDC_BUT_DEFAULT                 1255
#define IDC_RADIO_LINEIMPORT            1256
#define IDC_EDIT_UPSLAB_CORVERT         1256
#define IDC_COMBO_BRIDGE_NO             1257
#define IDC_EDIT_LOSLAB_CORVERT         1257
#define IDC_EDIT_FILEPATH               1258
#define IDC_COMBO_CTC                   1259
#define IDC_COMBO_CNS                   1260
#define IDC_COMBO_VIEWDOMYUN            1261
#define IDC_BUTTON_LINEOPEN             1263
#define IDC_COMBO_UPPER                 1264
#define IDC_RADIO_LINEINPUT             1266
#define IDC_COMBO_LOWER                 1267
#define IDC_BUTTON_ADD_ROW              1268
#define IDC_COMBO_CTC_PART              1269
#define IDC_BUTTON_DELETE_ROW           1270
#define IDD_DIALOG_EARTHQUACK           1271
#define IDD_DIALOG_BRIDGELEVEL          1272
#define IDD_DIALOG_EARTHQUACKGRADE      1273
#define IDD_DIALOG_EARTHFACT            1274
#define IDD_DIALOG_STEELFACT            1275
#define IDD_DIALOG_DONGBARI             1276
#define IDD_DIALOG_POST                 1277
#define IDC_BUTTON_EQLR                 1278
#define IDC_BUTTON_SYMLR                1279
#define IDC_STATIC_HELP                 1280
#define IDC_COMBO_INWALL                1281
#define IDD_DIALOG_BRIDGE_TYPE          1282
#define IDC_BUTTON_PLANE                1283
#define IDC_BUTTON_VERTICAL             1284
#define IDC_BUTTON_SLOPE                1285
#define IDC_STATIC_VIEW                 1286
#define IDC_RADIO_PLANE                 1287
#define IDC_STATIC_SETTING              1288
#define IDC_RADIO_VERTICAL              1289
#define IDC_BUTTON_MOVE_UP              1290
#define IDC_BUTTON_MOVE_DOWN            1291
#define IDC_BUTTON_COPY                 1292
#define IDC_BUTTON_NEW_ALL              1293
#define IDC_BUTTON_SAVE_INDIVISUAL      1294
#define IDC_RADIO_TYPE1                 1295
#define IDC_BUTTON_INSERT_INDIVISUAL    1296
#define IDC_RADIO_TYPE2                 1297
#define IDC_RADIO_TYPE3                 1298
#define IDC_RADIO_TYPE4                 1299
#define IDC_RADIO_TYPE5                 1300
#define IDC_RADIO_TYPE6                 1301
#define IDD_DIALOG_EXPJOINT             1302
#define IDC_RADIO_TYPE7                 1302
#define IDC_BUTTON_EXPJOINT             1303
#define IDC_STATIC1                     1304
#define IDC_STATIC2                     1305
#define IDC_STATIC4                     1306
#define IDC_EDIT_LINENAME               1307
#define IDC_STATIC_LINENAME             1308
#define IDC_BUTTON_INSERT_ROW           1309
#define IDC_EDIT_STATION_STT            1310
#define IDC_STATIC_STATION_STT          1311
#define IDC_STATIC_EL                   1312
#define IDB_BITMAP_BRITYPE0             1313
#define IDB_BITMAP_BRITYPE1             1314
#define IDB_BITMAP_BRITYPE2             1315
#define IDB_BITMAP_BRITYPE3             1316
#define IDB_BITMAP_BRITYPE4             1317
#define IDB_BITMAP_BRITYPE5             1318
#define IDC_STATIC_WALL                 1319
#define IDC_RADIO_TANGENT               1321
#define IDC_RADIO_RIGHTANG              1322
#define IDC_RADIO_FIXEDSHOE             1323
#define IDC_RADIO_CURRENT               1324
#define IDC_RADIO_CROSS                 1325
#define IDC_BUTTON_INSERT_COL           1326
#define IDC_BUTTON_DELETE_COL           1327
#define IDC_GROUP_DIST                  1328
#define IDC_GROUP_SECTION               1329
#define IDC_STATIC_THICK                1330
#define IDC_STATIC_TP                   1333
#define IDC_STATIC_TS                   1334
#define IDC_EDIT_TP                     1337
#define IDC_EDIT_TS                     1338
#define IDC_BUTTON_GUARDWALL            1339
#define IDD_DIALOG_GUARDWALL            1340
#define IDC_DOM                         1342
#define IDC_BUTTON_GUARDWALL_UNDER      1345
#define IDD_DIALOG_DOM                  1348
#define IDC_COMBO_FOOTING               1350
#define IDC_COMBO_KIND_PILE             1352
#define IDC_COMBO_GUGAN                 1353
#define IDC_COMBO_VERT_SU               1355
#define IDC_STATIC_VERT_SU              1357
#define IDD_DIALOG_PILE                 1358
#define IDC_COMBO_CROSS                 1359
#define IDC_COMBO_KIND_PILE2            1360
#define IDC_CHECK_BENTO                 1361
#define IDC_CHECK_GROUP                 1362
#define IDC_CHECK_FRICTION              1363
#define IDC_EDIT_ROADCENTER_LEVEL_LEFT  1364
#define IDC_STATIC_HEAD                 1365
#define IDC_EDIT_ROADCENTER_LEVEL_RIGHT 1366
#define IDC_STATIC_ROADCENTER_LEVEL_LEFT 1367
#define IDC_STATIC_KIND                 1368
#define IDC_STATIC_ROADCENTER_LEVEL_RIGHT 1369
#define IDC_TAB_POS                     1370
#define IDC_BUTTON_JEWON                1371
#define IDC_BUTTON_FINITE               1372
#define IDC_BUTTON_FCE                  1373
#define IDC_CHECK_SAME_DIST             1374
#define IDC_CHECK_CROSS                 1375
#define IDC_BUTTON_SAME                 1377
#define IDC_BUTTON_SLAB_SHAPE           1378
#define IDC_TAB1                        1379
#define IDC_RECOMMAND                   1380
#define IDC_CHECK_ORTHO                 1381
#define IDD_DIALOG_HYUNTA               1382
#define IDC_CHECK_WING                  1383
#define IDC_COMBO_DAN                   1384
#define IDD_DIALOG_SODAN                1385
#define IDC_CHECK_DIVISION              1386
#define IDC_BUTTON_RECOMMAND2           1387
#define IDC_CHECK_AUTOEL                1388
#define IDD_DIALOG_REBARJOINT           1389
#define IDD_DIALOG_REBARDAN             1391
#define IDC_CHECK_REAL                  1392
#define IDC_COMBO_STIRRUP               1393
#define IDC_TAB_INWALL                  1394
#define IDC_GRID_INWALL                 1395
#define IDC_GRID_RIB                    1397
#define IDC_STATIC_SCALE2               1398
#define IDD_EHP_POPUP                   1399
#define IDB_BITMAP_EVALUE               1400
#define IDD_DIALOG_REBAR_WINGWALL       1401
#define IDB_BITMAP_UVALUE               1402
#define IDB_BITMAP_HELPICON             1403
#define IDB_BITMAP_COMMENT              1404
#define IDD_DIALOG_CHECK_GRID           1405
#define IDD_DIALOG_CRACK_ENV            1406
#define IDD_DIALOG_MIDASREAD            1407
#define IDD_DIALOG_CHECK_EDIT           1408
#define IDD_DIALOG_OPTIMIZE             1409
#define IDD_DIALOG_HGPROGRESS           1410
#define IDB_BITMAP_BRITYPE6             1411
#define IDB_BITMAP_TANK                 1412
#define IDB_BITMAP_TRAILER              1413
#define IDD_DIALOG_CHECK_ARCHRIB        1414
#define IDB_BITMAP_EHP                  1415
#define IDD_DIALOG_HDAN_LENGTH          1416
#define IDD_DIALOG_BORINGMARK           1417
#define IDD_DIALOG_EVALUE               1418
#define IDD_DIALOG_UVALUE               1419
#define IDD_DIALOG_REBARHUNCH           1420
#define IDD_DIALOG_REBARSUPPORT         1421
#define IDD_DIALOG_REBARSHEAR           1422
#define IDD_DIALOG_ROUND                1423
#define IDD_DIALOG_STIRRUP              1424
#define IDD_DIALOG_APSSETTING           1425
#define IDC_RADIO_LEFTVIEW              1426
#define IDC_RADIO_RIGHTVIEW             1427
#define IDC_COMBO_BORING                1428
#define IDC_BUTTON_FOOTING_OPTIMIZE     1429
#define IDC_GRID_UPPERSLAB              1430
#define IDC_CHECK_FOOTING_SHAPE         1431
#define IDC_CHECK_ALLMARK               1432
#define IDC_EDIT_BORING_EL              1433
#define IDC_TAB_UPPERSLAB               1434
#define IDC_RADIO_CURRENT_DIM           1435
#define IDC_BUTTON_SUPPORT              1436
#define IDC_CHECK_BMD                   1437
#define IDC_GRID_LOWERSLAB              1438
#define IDC_RADIO_WHOLE_DIM             1439
#define IDC_BUTTON_SHEAR                1440
#define IDC_EDIT_BORING_STATION         1441
#define IDC_GRID_OUTWALL                1442
#define IDC_BUTTON_SAME_ANGLE           1443
#define IDC_TAB_REBAR                   1444
#define IDC_CHECK_FOOTING_LEN_FLOAT     1445
#define IDC_TAB_LOWERSLAB               1446
#define IDC_TAB_ROW                     1447
#define IDC_COMBO_SELECT                1448
#define IDC_STATIC_BORING_NAME          1449
#define IDC_COMBO_PLAN                  1449
#define IDC_BUTTON_EXP                  1450
#define IDC_CHECK_BMD1                  1451
#define IDC_BUTTON_AUTO_RADIUS_GAGAK    1452
#define IDC_STATIC_BORING               1453
#define IDC_BUTTON_EXP_JOINT            1453
#define IDC_TAB_OUTWALL                 1454
#define IDC_BUTTON_REF_EXP_JOINT        1454
#define IDC_STATIC_UPPER                1455
#define IDC_BUTTON_EXP_JOINT2           1455
#define IDC_BUTTON_SAME_EXP_JOINT       1455
#define IDC_COMBO_ROUND_IN              1456
#define IDC_CHECK_LEFTWALL_INNER        1457
#define IDC_STATIC_LOWER                1458
#define IDC_CHECK_STTWALL_INNER         1459
#define IDC_EDIT_BORING_NAME            1460
#define IDC_CHECK_INWALL_INNER          1461
#define IDC_CHECK_SAMEOFFSET_TANDC      1462
#define IDC_BUTTON_OPTION               1463
#define IDC_CHECK_PREVIEW               1464
#define IDC_STATIC_BORING_STATION       1465
#define IDC_CHECK_RIGHTWALL_INNER2      1466
#define IDC_CHECK_ENDWALL_INNER         1467
#define IDC_COMBO_ROUND                 1468
#define IDC_CHECK_MAINCTC_D             1469
#define IDC_CHECK_CUTTING_PILE          1470
#define IDC_CHECK_SAMEOFFSET            1471
#define IDC_STATIC_BORING_NUM           1472
#define IDC_CHECK_DANBU_BENDING         1473
#define IDC_CHECK_HUNCH                 1474
#define IDC_COMBO_ROUND_OUT             1475
#define IDC_STATIC_SHEAR                1476
#define IDC_CHECK_VIEW_EARTH            1477
#define IDC_CHECK_ADDREBAR_REINFORCE    1478
#define IDC_STATIC_GROUNDINFONUM        1479
#define IDC_CHECK_DAN                   1480
#define IDC_CHECK_VIEW_CROSS            1481
#define IDC_CHECK_23                    1482
#define IDC_COMBO_GROUNDINFONUM         1483
#define IDC_COMBO_NUM                   1484
#define IDC_COMBO_SIDE_COUNT            1485
#define IDC_COMBO_UPPER_COUNT           1486
#define IDC_COMBO_LOWER_COUNT           1487
#define IDC_COMBO_SHEAR_BIND            1488
#define IDC_COMBO_STD_VERCTC            1489
#define IDC_CHECK_UPPER_REBAR_SLOPE     1490
#define IDC_STATIC_COUNT_LOWER          1491
#define IDC_COMBO_MAINCTC_A             1492
#define IDC_STATIC_SLOPE_BLOCK_IN       1493
#define IDC_BUTTON_SETTING              1494
#define IDC_COMBO_SLOPE_BLOCK_IN        1495
#define IDC_COMBO_HUNCH_CTC             1496
#define IDC_STATIC_HUNCH_CTC            1497
#define IDC_COMBO_MAINCTC_B             1498
#define IDC_STATIC_MAINCTC_A            1499
#define IDC_STATIC_SLOPE_BLOCK_OUT      1500
#define IDC_COMBO_SLOPE_BLOCK_OUT       1501
#define IDC_STATIC_MAINCTC_B            1502
#define IDD_DIALOG_RAILLOAD             1503
#define IDC_COMBO_REBAR_CURVE           1504
#define IDC_SUBWAY_SELECT_COMBO         1505
#define IDC_STATIC_REBAR_CURVE          1506
#define IDC_SUBWAY_STATIC               1507
#define IDC_STATIC_COUNT_UPPER          1508
#define IDC_STATIC_REBAR_SHEAR_BC       1509
#define IDC_SUBWAY_STATIC2              1510
#define IDC_STATIC_COUNT_SIDE           1511
#define IDC_COMBO_REBAR_SHEAR_BC        1512
#define IDC_SUBWAY_STATIC3              1513
#define IDD_DIALOG_SLAB_SHAPE           1514
#define IDC_RADIO_V22                   1515
#define IDC_SUBWAY_WEIGHT               1516
#define IDD_DIALOG_EXP_WIDTH            1517
#define IDC_RADIO_M33                   1518
#define IDC_STATIC_COMMENT              1519
#define IDC_STATIC3                     1520
#define IDC_TAB_DESIGN_TYPE             1521
#define IDD_DIALOG_REBARDANBU           1522
#define IDC_CHECK_BRACKET               1523
#define IDC_HYPER_HELP                  1524
#define IDC_BITMAP_HELPICON             1525
#define IDD_DIALOG_TYPECYCLE3           1526
#define IDC_STATIC_UNIT                 1527
#define IDC_BITMAP_EO_SI                1528
#define IDC_STATIC_UNIT_FY              1529
#define IDC_CHECK_LEFTTOP               1530
#define IDC_BITMAP_EO                   1531
#define IDC_CHECK_RIGHTTOP              1532
#define IDC_STATIC_JUNC                 1535
#define IDC_CHECK_LEVEL_ROADCENTER      1536
#define IDC_STATIC_ELEM                 1537
#define IDC_CHECK_APPLY_LINE_SLOPE      1538
#define IDC_STATIC_DATA                 1539
#define IDC_STATIC_BACK_CLR             1541
#define IDC_COMBO_ROAD_MAT              1542
#define IDC_STATIC_ROAD_MAT             1543
#define IDC_STATIC_CALC                 1544
#define IDC_STATIC_OPTION               1545
#define IDC_STATIC_CNS                  1547
#define IDC_HDANIN_DIS_BASE_ELEVATION   1548
#define IDC_BUTTON_RUN_TOOL             1549
#define IDC_BUTTON_MAKE                 1551
#define IDC_BUTTON_LOAD_OUTPUT          1553
#define IDC_CHECK_LEFT                  1558
#define IDC_CHECK_STT                   1559
#define IDC_STATIC_LOAD1                1560
#define IDD_DIALOG_REBARJOINT_1CYCLE    1561
#define IDC_CHECK_RIGHT                 1562
#define IDC_STATIC_LOAD2                1563
#define IDC_CHECK_END                   1564
#define IDC_STATIC_LOAD3                1565
#define IDC_CHECK_SFD                   1566
#define IDC_STATIC_LOAD4                1567
#define IDC_RADIO_CRACK1                1568
#define IDC_STATIC_TONF1                1569
#define IDC_RADIO_CRACK2                1570
#define IDC_STATIC_TONF2                1571
#define IDC_RADIO_CRACK3                1572
#define IDC_STATIC_TONF3                1573
#define IDD_DIALOG_BRIDGE_TYPE_NONG     1574
#define IDC_RADIO_CRACK4                1575
#define IDC_STATIC_TONF4                1576
#define IDD_DIALOG_BRIDGE_TYPE_NORMAL   1577
#define IDC_RADIO_CRACK5                1578
#define IDC_STATIC_DB24_1               1579
#define IDC_RADIO_CRACK6                1580
#define IDC_STATIC_DB24_2               1581
#define IDC_RADIO_CRACK7                1582
#define IDC_STATIC_DB24_3               1583
#define IDC_RADIO_CRACK8                1584
#define IDC_STATIC_DB24_4               1585
#define IDC_RADIO_CRACK9                1586
#define IDC_STATIC_DB18_1               1587
#define IDC_STATIC_DB18_2               1588
#define IDC_STATIC_DB18_3               1589
#define IDC_STATIC_DB18_4               1590
#define IDC_STATIC_DB13_1               1591
#define IDC_STATIC_DB13_2               1592
#define IDC_STATIC_DB13_3               1593
#define IDC_STATIC_DB13_4               1594
#define IDC_STATIC_APS                  1595
#define IDC_RADIO_FXX                   1596
#define IDC_RADIO_FYY                   1597
#define IDC_RADIO_FXY                   1598
#define IDC_RADIO_FMAX                  1599
#define IDC_RADIO_FMIN                  1600
#define IDC_RADIO_MXX                   1601
#define IDC_RADIO_MYY                   1602
#define IDC_RADIO_MXY                   1603
#define IDC_RADIO_MMAX                  1604
#define IDC_RADIO_MMIN                  1605
#define IDC_RADIO_VXX                   1606
#define IDC_EDIT_FCK                    1607
#define IDC_RADIO_VYY                   1608
#define IDC_STATIC_FCK                  1609
#define IDC_STATIC_FCK2                 1610
#define IDC_PROGRESS_MIDAS              1611
#define IDC_EDIT_FY                     1612
#define IDC_EDIT_AGG                    1613
#define IDC_CHECK_VIEW_COUNTER_DIR      1614
#define IDC_STATIC_UNIT_FCK             1615
#define IDC_CHECK_VIEW_COUNTER_DIR2     1615
#define IDC_CHECK_PAD_SHOE              1615
#define IDC_RICHEDIT_CHECK              1616
#define IDC_CHECK_EXP                   1617
#define IDC_CHECK_AUTO_HDAN             1618
#define IDC_TAB2                        1619
#define IDC_STATIC_CTC_GIRDER           1620
#define IDC_EDIT_CTC_GIRDER             1621
#define IDC_STATIC_CTC_GIRDER2          1623
#define IDC_EDIT_CHECK                  1625
#define IDC_STATIC_RAIL_FL              1626
#define IDC_CHECK_STATION               1630
#define IDC_EDIT_HYUNGHA_STATION        1631
#define IDC_EDIT_HYUNGHA_EL             1632
#define IDC_STATIC_HYUNGHA              1633
#define IDC_STATIC_HYUNG_EL             1634
#define IDC_CHECK_MATCH_WITHWALL        1635
#define IDC_STATIC_FY                   1636
#define IDC_CHECK_QUICK_SEARCH          1637
#define IDC_STATIC_AGG                  1638
#define IDC_COMBO_DANBU                 1639
#define IDC_STATIC_GW_GUGAN             1640
#define IDC_COMBO_GW_GUGAN              1641
#define IDC_COMBO_OBTUSE                1642
#define IDC_STATIC_UPPER_GUGAN          1643
#define IDC_COMBO_ACUTE                 1644
#define IDC_COMBO_UPPER_GUGAN           1645
#define IDC_STATIC_SIDE_GUGAN           1646
#define IDC_COMBO_SIDE_GUGAN            1647
#define IDC_CHECK_AUTO_COMBINE          1648
#define IDC_COMBO_DIA_MIN               1649
#define IDC_COMBO_DIA_MAX               1650
#define IDC_EDIT_SAFE_RATE              1651
#define IDC_CHECK_REBAR_2DAN            1652
#define IDC_CHECK_SPLITE_CYCLE          1653
#define IDC_STATIC_HGMESSAGE            1654
#define IDC_CHECK_REBAR_MATCH           1655
#define IDC_STATIC_HGMESSAGE2           1656
#define IDC_CHECK_VIEW_PM               1657
#define IDC_STATIC_OTHER_FCK            1658
#define IDC_STATIC_OTHER_FY             1659
#define IDC_COMBO_SHOE_EA               1660
#define IDC_COMBO_INPUT_COLUMN          1661
#define IDC_STATIC_SHOE_EA              1662
#define IDC_CHECK_SAMEDIST              1663
#define IDC_CHECK_PILE_KIND             1665
#define IDC_CHECK_DIST                  1666
#define IDC_BITMAP_TANK                 1670
#define IDC_BITMAP_TRAILER              1671
#define IDC_GROUPBOX_TANK               1672
#define IDC_GROUPBOX_TRAILER            1673
#define IDC_EDIT_TANK_LENGTH            1674
#define IDC_EDIT_TANK_WIDTH_SIDE        1675
#define IDC_EDIT_TANK_WIDTH_TOT         1676
#define IDC_EDIT_TANK_WIDTH_INNER       1677
#define IDC_EDIT_TRAILER_L1             1678
#define IDC_EDIT_TRAILER_L2             1679
#define IDC_EDIT_TRAILER_L3             1680
#define IDC_EDIT_TRAILER_L4             1681
#define IDC_EDIT_TRAILER_WIDTH_SIDE     1682
#define IDC_EDIT_TRAILER_WIDTH_INNER    1683
#define IDC_EDIT_TRAILER_WIDTH_TOT      1684
#define IDC_EDIT_TANK_FACT_I            1685
#define IDC_TEXT1                       1686
#define IDC_TEXT2                       1687
#define IDC_TEXT3                       1688
#define IDC_TEXT4                       1689
#define IDC_TEXT6                       1690
#define IDC_TEXT7                       1691
#define IDC_CHECK_USER_PLATE_OUTPUT     1692
#define IDC_TEXT8                       1693
#define IDC_EDIT_TANK_WEIGHT            1694
#define IDC_CHECK_POSITION              1695
#define IDC_EDIT_TRAILER_I              1696
#define IDC_EDIT_TRAILER_FACT_I         1697
#define IDC_EDIT_TRAILER_I2             1698
#define IDC_TEXT11                      1699
#define IDC_EDIT_TRAILER_P1             1700
#define IDC_EDIT_TRAILER_I3             1701
#define IDC_STATIC_RIB                  1702
#define IDC_EDIT_TRAILER_P2             1703
#define IDC_EDIT_TRAILER_I4             1704
#define IDC_CHECK_GWHALF                1705
#define IDC_EDIT_TRAILER_P3             1706
#define IDC_TEXT12                      1707
#define IDC_TAB_RIB                     1708
#define IDC_DOM_RIB                     1709
#define IDC_EDIT_ACCU                   1710
#define IDC_STATIC_ACCU                 1711
#define IDC_STATIC_PART                 1713
#define IDC_TEXT_TOOLNAME               1714
#define IDC_CHECK_KOR                   1715
#define IDC_CHECK_2DAN                  1716
#define IDC_EDIT_LOAD1                  1717
#define IDC_CHECK_BENDING               1718
#define IDC_EDIT_LOAD2                  1719
#define IDC_EDIT_LOAD3                  1720
#define IDC_EDIT_LOAD4                  1721
#define IDC_EDIT_LOAD5                  1722
#define IDC_STATIC_LOAD5                1723
#define IDC_CHECK_DETAILINPUT_23DAN     1724
#define IDC_COMBO3                      1725
#define IDC_COMBO_DIGGING_POS           1725
#define IDC_CHECK_VIEW_CYCLE1           1726
#define IDC_CHECK_VIEW_CYCLE2           1727
#define IDC_COMBO_TOOLNAME              1728
#define IDC_CHECK_VIEW_HATCH            1729
#define IDC_EDIT_STA                    1730
#define IDC_EDIT_ANG                    1731
#define IDC_EDIT_IP_HEIGHT              1732
#define IDC_STATIC_IP_HEIGHT            1733
#define IDC_CHECK_CONC_STRESS           1734
#define IDC_TEXT5                       1735
#define IDC_TEXT9                       1736
#define IDC_TEXT10                      1737
#define IDC_STATIC_TEXT_LINK            1738
#define IDC_BUTTON_LINK                 1739
#define IDB_BITMAP_BOR1                 1740
#define IDB_BITMAP_BOR2                 1741
#define IDB_BITMAP_BOR3                 1742
#define IDB_BITMAP_BOR4                 1743
#define IDB_BITMAP_BOR5                 1744
#define IDB_BITMAP_BOR6                 1745
#define IDB_BITMAP_BOR7                 1746
#define IDB_BITMAP_BOR8                 1747
#define IDB_BITMAP_BOR9                 1748
#define IDB_BITMAP_BOR10                1749
#define IDB_BITMAP_BOR11                1750
#define IDB_BITMAP_BOR12                1751
#define IDB_BITMAP_BOR13                1752
#define IDB_BITMAP_BOR14                1753
#define IDB_BITMAP_BOR15                1754
#define IDB_BITMAP_BOR16                1755
#define IDB_BITMAP_BOR17                1756
#define IDB_BITMAP_BOR18                1757
#define IDB_BITMAP_BOR19                1758
#define IDB_BITMAP_BOR20                1759
#define IDB_BITMAP_BOR21                1760
#define IDB_BITMAP_BOR22                1761
#define IDB_BITMAP_BOR23                1762
#define IDB_BITMAP_BOR24                1763
#define IDB_BITMAP_BOR25                1764
#define IDB_BITMAP_BOR26                1765
#define IDB_BITMAP_BOR27                1766
#define IDB_BITMAP_BOR28                1767
#define IDB_BITMAP_BOR29                1768
#define IDB_BITMAP_BOR30                1769
#define IDB_BITMAP_BOR31                1770
#define IDB_BITMAP_BOR32                1771
#define IDB_BITMAP_BOR33                1772
#define IDB_BITMAP_BOR34                1773
#define IDB_BITMAP_BOR35                1774
#define IDB_BITMAP_BOR36                1775
#define IDB_BITMAP_BOR37                1776
#define IDB_BITMAP_EVALUE_SI            1777
#define IDB_BITMAP_DONGBARI2            1778
#define IDD_BASE1_PROJECTINFO           1779
#define IDD_BASE2_DESIGN_BASICDATA      1780
#define IDD_BASE3_LINEINFO              1781
#define IDD_BASE4_BRIDGE_FORMFACTOR     1782
#define IDD_BASE6_CROSS_POSITION        1783
#define IDD_BASE7_SPAN_CONSTRUCT        1784
#define IDD_BASE8_SHOE_POSITION         1785
#define IDD_BASE9_CROSS_CONSTRUCT       1786
#define IDD_BASE5_GROUNDINFO            1787
#define IDD_GEN_DESIGN_VARIABLE         1788
#define IDD_GEN_JONG_SECTION            1789
#define IDD_GEN_COLUMN                  1790
#define IDD_GEN_FOOTING                 1791
#define IDD_GEN_APS                     1792
#define IDD_GEN_WINGWALL                1793
#define IDD_GEN_PLANE                   1794
#define IDD_GEN_HYUNTA                  1795
#define IDD_GEN_SODAN                   1796
#define IDD_GEN_FRAME_ANLYSIS           1797
#define IDD_GEN_SHELL_ANLYSIS           1798
#define IDD_GEN_EARTHQUAKE_ANLYSIS      1799
#define IDD_GEN_TOGONG                  1800
#define IDD_GEN_MONUMENT                1801
#define IDD_REBAR_MAIN                  1802
#define IDD_REBAR_SECTION               1803
#define IDD_REBAR_COLUMN                1804
#define IDD_REBAR_WINGWALL              1805
#define IDD_REBAR_OTHERS                1806
#define IDD_REBAR_JEWON                 1807
#define IDD_REBAR_APS                   1808
#define IDD_REBAR_MAIN2                 1809
#define IDD_REBAR_MAIN3                 1810
#define IDD_REBAR_MAIN4                 1811
#define IDD_REBAR_GAGAK                 1812
#define IDC_CHECK_USER_DISPMAX          1814
#define IDD_DIALOG_FCE                  1814
#define IDB_BITMAP_FCE                  1815
#define IDC_EDIT_DISPMAX                1816
#define IDD_GEN_WING_SHELL_ANLYSIS      1817
#define IDC_CHECK_RAD_CROSSTIE          1818
#define IDD_DIALOG_DANCORNER            1819
#define IDB_BITMAP_BRITYPE7             1820
#define IDD_STM_CONDITION               1820
#define IDD_STM_ARC_CORNER              1821
#define IDC_SPIN_ARCBRIDGE              1822
#define IDD_STM_BRACKET                 1822
#define IDC_EDIT_EL                     1823
#define IDC_SPIN_STMCOMBO               1823
#define IDD_STM_FOORING_STARTEND        1823
#define IDC_SPIN_LOADCASE               1824
#define IDD_STM_FOORING_MID             1824
#define IDC_COMBO1                      1825
#define IDC_COMBO_ARCBRIDGE             1825
#define IDC_COMBO_SELECT_WING           1826
#define IDC_COMBO_STMCOMBO              1826
#define IDD_DIALOG_STM_FOOTING_MAIN     1826
#define IDD_DIALOG_STM_ARCCORNER_MAIN   1826
#define IDC_BUTTON_SAME_ALL             1827
#define IDD_DIALOG_STM_SETTING          1827
#define IDC_COMBO_STMCOMBO_CHECK        1827
#define IDC_SPIN_LOADCOMBO              1828
#define IDD_DIALOG_STM_FOOTING_MAIN1    1828
#define IDC_SPIN_STMCOMBO_CHECK         1828
#define IDD_DIALOG_STM_BRACKET_MAIN     1830
#define IDD_DIALOG_STM_FOOTING_MAIN_STARTEND 1831
#define IDD_DIALOG_STM_FOOTING_MAIN_MID 1832
#define IDD_DIALOG_STM_ARCCORNER_SHEAR  1833
#define IDD_DIALOG_STM_BRACKET_SHEAR    1834
#define IDC_BTN_STMSETTING              1835
#define IDC_BTN_DEFAULTMODEL            1836
#define IDD_DIALOG_STM_FOOTING_SHEAR_STARTEND 1836
#define IDC_BTN_RENUM                   1837
#define IDD_DIALOG_STM_FOOTING_SHEAR_MID 1837
#define IDC_CHECK_LOAD                  1838
#define IDD_DIALOG_COMMAND_RESULT       1838
#define IDC_CHECK_STRUT_TIE             1839
#define IDD_GEN_LOAD                    1839
#define IDC_CHECK_NODAL_ZONE            1840
#define IDC_CHECK_STRESS_FLOW           1841
#define IDC_BTN_VIEWOPTION              1842
#define IDC_STATIC_VIEWCONTROL          1843
#define IDC_STATIC_CONDITON             1844
#define IDC_COMBO_DESIGN_TOOL           1846
#define IDC_BUTTON2                     1847
#define IDC_BUTTON_REMOVE_USER          1847
#define IDC_BUTTON_DEL_LINE             1847
#define IDC_BUTTON_SOLVER               1848
#define IDC_BUTTON_INPUT                1849
#define IDC_BUTTON_OUTPUT               1850
#define IDC_BTN_CHECKDESIGN             1851
#define IDC_BTN_CHECKMAIN               1852
#define IDC_BTN_CHECKSHEAR              1853
#define IDC_CHECK_ALLBRACKET            1857
#define IDC_CHECK_ALLFOOTING            1858
#define IDC_BUTTON_RUNSTRESSFLOW        1860
#define IDC_BUTTON_COMMAND_GO_ERROR     1861
#define IDC_BUTTON_COMMAND_GO_WARNING   1862
#define IDC_LIST1                       1863
#define IDC_LIST_RESULT_COMMAN_RESULT   1863
#define IDC_CHECK_VIEW_LSDINFO          1864
#define IDC_BUTTON_RESET_DETAILCOMBOA   1865
#define IDC_TAB_LSDETA                  1866
#define IDB_BITMAP_LSDBRIDGELEVEL       1867
#define IDC_CHECK_SHOW_USELOAD          1867
#define IDD_DIALOG_BRIDGELEVEL_LSD      1868
#define IDC_CHECK_AUTO_COMBIN_INIT      1868
#define IDD_DIALOG_ALPHAEVALUE          1869
#define IDC_STATIC_EL_UNIT              1869
#define IDC_STATIC_GROUND               1870
#define IDB_BITMAP_ALPHAE               1871
#define IDC_BITMAP_EO_LSD               1871
#define IDB_BITMAP_MS                   1872
#define IDC_STATIC_ELASTIC_INPUT        1872
#define IDD_DIALOG_MSVALUE              1873
#define IDC_STATIC_LSD                  1873
#define IDB_BITMAP_E_LSD                1874
#define IDC_STATIC_POISSON_INPUT        1874
#define IDB_BITMAP_U_LSD                1875
#define IDC_STATIC_POASONG_GROUP        1875
#define IDD_DIALOG_RAILLOAD_ALWAYS      1876
#define IDC_CHECK_VIEW_PLANE            1877
#define IDC_CHECK_VIEW_END_CROSS        1878
#define IDC_BUTTON_ADD_USER             1879
#define IDC_BUTTON_ADD_USER2            1880
#define IDD_DIALOG1                     1880
#define IDD_DIALOG_SET_EXPANSTION_JOIN_SPACE 1880
#define IDD_DIALOG_CHECK_CANTILEVER     1881
#define IDC_BUTTON_CANTILEVER           1882
#define IDD_DIALOG_DESIGN_REVIEW        1883
#define IDC_STATIC_MESH_SIZE            1884
#define IDD_DIALOG_EARTHQUACKGRADE_KDS17 1884
#define IDD_DIALOG_EARTHFACT_KDS17      1885
#define IDC_COMBO_MESH_SIZE             1886
#define IDC_BUTTON_CALC_SW              1887
#define IDC_BUTTON_CALC_EXPANSION       1888
#define IDC_BUTTON_INIT                 1889
#define IDC_STATIC_GROUP_BOX            1890
#define IDC_RADIO3                      1891
#define IDC_STATIC_SELECT               1892
#define IDC_COMBO_LINESELECT            1893
#define IDC_BUTTON_LINESAVE             1894
#define IDC_STATIC_GROUP2               1895
#define IDC_STATIC_NAME                 1896
#define IDC_BUTTON_ADD_LINE             1897
#define IDC_EDIT1                       1900
#define IDC_CHECK1                      1901
#define IDC_CHK_UPPERSLAB               1901
#define IDC_CHECK_AUTO_HEIGHT_SOIL      1901
#define IDC_CHECK_UPSLAB_CORVERT        1901
#define IDC_CHECK_DOWELREBAR_SEP        1902
#define IDC_CHECK_UPSLAB_CORVERT2       1902
#define IDC_CHECK_LOSLAB_CORVERT        1902
#define IDC_CHECK_ETA_COMBIN_EACH       1903
#define IDC_CHECK2                      1904
#define IDC_CHK_LOWERSLAB               1905
#define IDC_STATIC_DIGGING_POS          1905
#define IDC_BUTTON_JOINT                1906
#define IDC_STATIC_EQ1                  1908
#define IDC_STATIC_EQ2                  1909
#define IDC_STATIC_EQ3                  1910
#define IDC_STATIC_EQ4                  1911
#define ID_BUTTON_APPLY                 3010
#define IDC_BUTTON_DEL                  3115
#define IDC_BUTTON_USER_ADD             3615
#define IDC_BUTTON_DEFAULT1             3616
#define IDC_STATIC_ANGLE                4099
#define IDC_STATIC_SCALE                4120
#define ID_BUTTON_RECOMMAND             5004
#define IDC_RADIO_LEFT                  5061
#define IDC_RADIO_RIGHT                 5062
#define ID_BUTTON_FINITE_PILE           7200
#define ID_BUTTON_HYUNTA_PILE           7201
#define IDC_STATIC_MM                   8086
#define IDC_STATIC_DIR                  15376
#define ID_INPUT_BASE1                  20771
#define ID_INPUT_BASE2                  20772
#define ID_INPUT_BASE3                  20773
#define ID_INPUT_BASE4                  20774
#define ID_INPUT_BASE5                  20775
#define ID_INPUT_BASE6                  20776
#define ID_INPUT_BASE7                  20777
#define ID_INPUT_BASE8                  20778
#define ID_INPUT_BASE9                  20779
#define ID_INPUT_GENERAL1               20780
#define ID_INPUT_GENERAL2               20781
#define ID_INPUT_GENERAL3               20782
#define ID_INPUT_GENERAL4               20783
#define ID_INPUT_GENERAL5               20784
#define ID_INPUT_GENERAL6               20785
#define ID_INPUT_GENERAL7               20786
#define ID_INPUT_GENERAL8               20787
#define ID_INPUT_GENERAL9               20788
#define ID_INPUT_GENERAL10              20789
#define ID_INPUT_GENERAL11              20790
#define ID_INPUT_GENERAL12              20791
#define ID_INPUT_GENERAL13              20792
#define ID_INPUT_GENERAL14              20793
#define ID_INPUT_REBAR1                 20794
#define ID_INPUT_REBAR2                 20795
#define ID_INPUT_REBAR3                 20796
#define ID_INPUT_REBAR4                 20797
#define ID_INPUT_REBAR5                 20798
#define ID_INPUT_REBAR6                 20799
#define ID_INPUT_REBAR7                 20800
#define ID_INPUT_REBAR8                 20801
#define ID_INPUT_REBAR9                 20802
#define ID_INPUT_REBAR10                20803
#define ID_INPUT_STM1                   20804
#define ID_INPUT_STM2                   20805
#define ID_INPUT_STM3                   20806
#define ID_INPUT_STM4                   20807
#define ID_INPUT_STM5                   20808
#define IDS_PHC_WARNING                 20809
#define IDC_TAB                         26973
#define IDC_BUTTON_HYUNTA               26974

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1887
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1912
#define _APS_NEXT_SYMED_VALUE           8001
#endif
#endif
