copy ..\..\..\Lib\opengl32.dll ..\commonCompile\Output\ > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\ALDKDlg.dll ..\commonCompile\Output\ > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\HgExport.dll ..\commonCompile\Output\ > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\ShareBridgeInfo.dll ..\commonCompile\Output\ > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\ShareWithADManager.dll ..\commonCompile\Output\ > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\ShGrid.dll ..\commonCompile\Output\ > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\ShControlBar.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\Domyun.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\ShImageMng.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\LineApp.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\DrawManage.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\AException.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\ARoadConfig.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\XLReport.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Lib\XTPToolkitPro\CommonCompile\Output\ToolkitPro1211vc60.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\ToolkitPro1211vc90.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\XTPExtvc60.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\XTPExtvc90.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\HGGhostConc.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\HGBaseConc.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\HGBaseDesign.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\HGBaseDraw.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\AFem.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\Data\HgExcelBase.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\Src\HgBaseDraw\HCAD_Symbol.dxf ..\commonCompile\Output\ > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\ALine.exe ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\ABorder.exe ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\AEdit.exe ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Dll\sx32w.dll ..\commonCompile\Output\ 
copy ..\..\..\Dll\opengl32.dll ..\CommonCompile\Output\ > ..\CommonCompile\Output\out
copy ..\..\..\Engine\BaseComp\CommonCompile\Output\RCModule.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseComp\CommonCompile\Output\HgBaseBM.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseComp\CommonCompile\Output\MeshGen.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\CommonBridge.dll ..\commonCompile\Output\ > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\BearingInfo.dll ..\commonCompile\Output\ > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\CommonCompile\Output\HGDBControl.dll ..\commonCompile\Output\ > ..\commonCompile\Output\out 
copy ..\..\..\Engine\FrameEng\CommonCompile\Output\HgOccView.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\Bim3DEng\CommonCompile\Output\*.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Lib\Ubicon_Occ\CommonCompile\Output\*.dll ..\commonCompile\Output\  > ..\commonCompile\Output\out 
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝550.dxf ..\commonCompile\Output\ > ..\commonCompile\Output\out
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝700.dxf ..\commonCompile\Output\ > ..\commonCompile\Output\out
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝900.dxf ..\commonCompile\Output\ > ..\commonCompile\Output\out
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝1200.dxf ..\commonCompile\Output\ > ..\commonCompile\Output\out
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝1450.dxf ..\commonCompile\Output\ > ..\commonCompile\Output\out
copy ..\Data\Dxf\chairblock_spacer설치위치_상세.dxf ..\commonCompile\Output\ > ..\commonCompile\Output\out
copy ..\Data\Dxf\chairblock_전단철근_상세.dxf ..\commonCompile\Output\ > ..\commonCompile\Output\out
copy ..\Data\Dxf\chairblock_피복유지_상세.dxf ..\commonCompile\Output\ > ..\commonCompile\Output\out
copy ..\Patch\Upgrade.txt ..\commonCompile\Output\ > ..\commonCompile\Output\out