copy ..\..\..\Lib\opengl32.dll ..\CommonCompile\OutputD\ > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\ALDKDlgD.dll ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\HgExportD.dll ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\ShareBridgeInfoD.dll ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\ShareWithADManagerD.dll ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\ShGridD.dll ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\ShControlBarD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\DomyunD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\ShImageMngD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\LineAppD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\DrawManageD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\AExceptionD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\ARoadConfigD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\XLReportD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Lib\XTPToolkitPro\CommonCompile\OutputD\ToolkitPro1211vc60D.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\ToolkitPro1211vc90D.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\XTPExtvc60D.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\XTPExtvc90D.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\HGGhostConcD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\HGBaseConcD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\HGBaseDesignD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\HGBaseDrawD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\AFemD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\Data\HgExcelBase.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\Src\HgBaseDraw\HCAD_Symbol.dxf ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\ALine.exe ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\ABorder.exe ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\AEdit.exe ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Dll\sx32w.dll ..\commonCompile\OutputD\ 
copy ..\..\..\Dll\opengl32.dll ..\CommonCompile\OutputD\ > ..\CommonCompile\OutputD\outD
copy ..\..\..\Engine\BaseComp\CommonCompile\OutputD\RCModuleD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseComp\CommonCompile\OutputD\HgBaseBMD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseComp\CommonCompile\OutputD\MeshGenD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\CommonBridgeD.dll ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\BearingInfoD.dll ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD\HGDBControlD.dll ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\FrameEng\CommonCompile\OutputD\HgOccViewD.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\Bim3DEng\CommonCompile\OutputD\*.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Lib\Ubicon_Occ\CommonCompile\OutputD\*.dll ..\commonCompile\OutputD\  > ..\CommonCompile\OutputD\outD 
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝550.dxf ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝700.dxf ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝900.dxf ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝1200.dxf ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝1450.dxf ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD
copy ..\Data\Dxf\chairblock_spacer설치위치_상세.dxf ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD
copy ..\Data\Dxf\chairblock_전단철근_상세.dxf ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD
copy ..\Data\Dxf\chairblock_피복유지_상세.dxf ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD
copy ..\Patch\Upgrade.txt ..\commonCompile\OutputD\ > ..\CommonCompile\OutputD\outD