copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\ALDKDlgD.dll ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\HgExportD.dll ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\ShareBridgeInfoD.dll ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\ShareWithADManagerD.dll ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\ShGridD.dll ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\ShControlBarD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\DomyunD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\LineAppD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\DrawManageD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\AExceptionD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\ARoadConfigD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\XLReportD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\HGGhostConcD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\HGBaseConcD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\HGBaseDesignD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\HGBaseDrawD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\AFemD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\ALine.exe ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\ABorder.exe ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\ACommonUID.dll ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\CommonBridgeD.dll ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\BearingInfoD.dll ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\HGDBControlD.dll ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\CommonCompile\OutputD_v100\HgLsdD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\Data\Dxf\HCAD_Symbol.dxf ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝550.dxf ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝700.dxf ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝900.dxf ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝1200.dxf ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\Data\Dxf\내진말뚝1450.dxf ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseEng\i18n\Language.xml ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD

copy ..\..\..\Engine\BaseComp\CommonCompile\OutputD_v100\RCModuleD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseComp\CommonCompile\OutputD_v100\HgBaseBMD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\BaseComp\CommonCompile\OutputD_v100\MeshGenD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD

copy ..\..\..\Engine\HgModel3D\CommonCompile\OutputD_v100\*.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\HgModel3D\Data\*.shx ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD

copy ..\..\..\Engine\HgStm\CommonCompile\OutputD_v100\*.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\HgStm\Data\STAD\pconvertLsd.exe ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\HgStm\Data\STAD\tconvertLsd.exe ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\HgStm\Data\STAD\pconvertUsd.exe ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\HgStm\Data\STAD\tconvertUsd.exe ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Engine\HgStm\Data\STAD\truss.exe ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD

copy ..\..\..\Lib\XTPToolkitPro\CommonCompile\OutputD_v100\ToolkitPro1624vc100D.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Lib\XTPToolkitPro\Source\Styles\VisualStudio2012.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Lib\XTPExt\CommonCompile\OutputD_v100\XTPExtvc100D.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Lib\ShImageMng\CommonCompile\OutputD_v100\ShImageMngD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Lib\CM2\SurfRemeshQ4\*.dll ..\CommonCompile\OutputD_v100\*.dll  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Lib\CM2\QuadMesh\*.dll ..\CommonCompile\OutputD_v100\*.dll  > ..\CommonCompile\OutputD_v100\outD
copy ..\..\..\Lib\iconv\dll_win32\libiconvD.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD

copy ..\..\..\Dll\libiconv2.dll ..\commonCompile\OutputD_v100\  > ..\commonCompile\OutputD_v100\outD
copy ..\..\..\Dll\libintl3.dll ..\commonCompile\OutputD_v100\  > ..\commonCompile\OutputD_v100\outD
copy ..\..\..\Dll\sx32w.dll ..\commonCompile\OutputD_v100\  > ..\commonCompile\OutputD_v100\outD
copy ..\..\..\Tool\HGEdit\CommonCompile\OutputD_v100\AEdit.exe ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\Data\HgExcelBase.dll ..\commonCompile\OutputD_v100\  > ..\CommonCompile\OutputD_v100\outD
copy ..\Data\Dxf\chairblock_spacer설치위치_상세.dxf ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\Data\Dxf\chairblock_전단철근_상세.dxf ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\Data\Dxf\chairblock_피복유지_상세.dxf ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\Data\Dxf\교대보호블럭(육교용).dxf ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\Data\Dxf\교대보호블럭(하천용).dxf ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
copy ..\Patch\Upgrade.txt ..\commonCompile\OutputD_v100\ > ..\CommonCompile\OutputD_v100\outD
