//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ARcBridge.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DIALOG_WMFSIZE              101
#define IDD_DIALOG_SAVE_COMPLETE        102
#define IDR_MANIFEST                    103
#define IDR_MAINFRAME                   104
#define IDR_ARCBRITYPE                  105
#define IDR_INSERT_INPUTMENU            106
#define IDC_ACTIVESIZE                  106
#define IDC_ACTIVESIZE_UD               106
#define IDR_POPUP_ZOOM                  107
#define IDC_ACTIVESIZE_LR               107
#define IDR_POPUP_ORDER                 108
#define IDC_ACTIVESIZE_UPLR             108
#define IDC_ACTIVESIZE_UDLR             108
#define IDB_SPLASH                      109
#define IDR_TOOLBAR_DRAW                110
#define IDR_TOOLBAR_OUTPUT              111
#define IDR_TOOLBAR_FORMAT              112
#define IDR_TOOLBAR_ZOOM                113
#define IDR_TOOLBAR_OSNAP               114
#define IDR_TOOLBAR_ALIGN               115
#define IDR_TOOLBAR_OTHERS              116
#define IDB_BITMAP_ABOUT                117
#define IDR_TOOLBAR_BASE                118
#define IDR_TOOLBAR_GENERAL             119
#define IDR_TOOLBAR_REBAR               120
#define IDR_TOOLBAR_STM                 121
#define IDD_DIALOG_OCCVIEW_SELECT       122
#define IDB_BITMAP_DRAWING              123
#define IDB_BITMAP_SHORTCUTS_BIG        124
#define IDB_BITMAP_SHORTCUTS_SMALL      125
#define IDB_BITMAP_SUPPORT              126
#define IDB_BITMAP_INPUT_HEAD           127
#define IDR_ALIGN_UNDO                  128
#define IDB_BITMAP_ABOUT_PLUS           128
#define IDR_ALIGN_REDO                  129
#define IDB_SPLASH_PLUS                 129
#define IDR_POPUP_ZOOM_DEBUG            130
#define IDB_BITMAP1                     135
#define IDD_DIALOG_MENU_OUTBM           150
#define IDC_TAB_BM                      151
#define IDC_TREE_BM                     152
#define IDC_BUTTON_SELECT_ALL           153
#define IDC_BUTTON_SELECT_NONE          154
#define IDC_BUTTON_SELECT_REV           155
#define IDC_BUTTON_SELECT_BM            156
#define IDC_BUTTON_SELECT_BMSUM         157
#define IDC_BUTTON_BM                   158
#define ID_INDICATOR_VERSION            200
#define ID_VIEW_CONTROLPANE             201
#define ID_VIEW_INPUTPANE               202
#define ID_DRAW_CHANGE_PAGE             203
#define ID_EXPORT_DXF_CUR               204
#define ID_EXPORT_WMF_CUR               205
#define ID_EXPORT_LINE                  206
#define ID_DRAWING_OPTION               207
#define ID_DRAWING_EXPORT               208
#define ID_STRUCT_OUT                   209
#define ID_GEN_OUT                      210
#define ID_COMMON_OUT                   211
#define ID_EARTH_OUT                    212
#define IDC_TEDIT_PAGE                  213
#define IDC_TCOMBO_BRIDGE               214
#define IDC_TCOMBO_CATEGORY             215
#define ID_CATEGORY_ORDER               216
#define ID_CURRENT_PAGE                 217
#define ID_NEXT_PAGE                    218
#define ID_PREV_PAGE                    219
#define ID_NEXT_CATEGORY                220
#define ID_PREV_CATEGORY                221
#define ID_FIRST_CATEGORY               222
#define ID_LAST_CATEGORY                223
#define ID_INIT_DRAWING                 224
#define ID_SET_LAYER                    225
#define ID_SET_LINE                     226
#define ID_SET_FONT                     227
#define ID_SET_DIM                      228
#define ID_CALC_STATION                 229
#define ID_CALC_LINEINFO                230
#define ID_ZOOM_ALL                     231
#define ID_ZOOM_WINDOW                  232
#define ID_ZOOM_PREV                    233
#define ID_ZOOM_DYNAMIC                 234
#define ID_ZOOM_IN                      235
#define ID_ZOOM_OUT                     236
#define ID_REALTIME_ZOOM                237
#define ID_REALTIME_MOVE                238
#define ID_SNAP_END                     239
#define ID_SNAP_MIDDLE                  240
#define ID_SNAP_INTERSECTION            241
#define ID_SNAP_CENTER                  242
#define ID_SNAP_QUATER                  243
#define ID_SNAP_TANGENT                 244
#define ID_SNAP_PERPEN                  245
#define ID_SNAP_NODE                    246
#define ID_SNAP_NEAR                    247
#define ID_OBJECT_INFO                  248
#define ID_ADD_NOTE                     249
#define ID_MEASURE_DIST                 250
#define ID_ORDER_FRONT                  251
#define ID_ORDER_BACK                   252
#define ID_ORDER_APPLYSAME              253
#define ID_SET_CREATION                 254
#define ID_SELECT_OBJECT                255
#define ID_ALIGN_LEFT                   256
#define ID_ALIGN_CENTER_HOR             257
#define ID_ALIGN_RIGHT                  258
#define ID_ALIGN_TOP                    259
#define ID_ALIGN_CENTER_VER             260
#define ID_ALIGN_BOTTOM                 261
#define ID_ALIGN_SPACE_ACROSS           262
#define ID_ALIGN_SPACE_DOWN             263
#define ID_ALIGN_ATTACH_HOR             264
#define ID_ALIGN_ATTACH_VER             265
#define ID_OBJECT_ALIGN                 266
#define ID_VIEW_COMMENT                 268
#define ID_APP_HELP                     269
#define ID_APP_HOME                     270
#define ID_APP_QNA                      271
#define ID_APP_UPDATE                   272
#define ID_ALIGN_UNDO                   273
#define ID_ALIGN_REDO                   274
#define ID_ALIGN_UNDO_DUMMY             275
#define ID_ALIGN_REDO_DUMMY             276
#define IDD_DIALOG_UPDATE               277
#define ID_BUTTON_ADOMMANAGER           282
#define ID_BLOCK_PASTE                  282
#define ID_BLOCK_CUT                    284
#define ID_BLOCK_CANCEL                 286
#define ID_BLOCK_COPY                   287
#define ID_BLOCK_INIT_CUR               288
#define ID_BLOCK_INIT_ALL               289
#define ID_EXPORT_BRIDGEINFO            290
#define IDC_EDIT_WMFWIDTH               291
#define IDD_DIALOG_WAITFORPROGRAM       292
#define IDC_EDIT_WMFHEIGHT              293
#define IDD_DIALOG_INPUT_REBARSHEAR     294
#define IDC_CHECK_AUTOSIZE              295
#define IDC_STATIC_URL                  296
#define IDC_STATIC_EMAIL                297
#define IDC_STATIC_USER                 298
#define IDC_STATIC_COMPANY              299
#define IDC_STATIC_ID                   300
#define IDC_GRID2                       301
#define IDC_STATIC_BITMAP               303
#define IDC_DLGOCC_STATIC_3D            304
#define IDC_DLGOCC_RADIO_ALL            305
#define IDC_DLGOCC_RADIO_SELECT         306
#define IDC_DLGOCC_STATIC_OPTION        307
#define IDC_DLGOCC_CHECK_REBAR          308
#define IDC_STATIC_REBARKIND            309
#define IDC_DLGOCC_BUTTON_3D            310
#define IDC_DLGOCC_COMBO_RC             311
#define IDC_BUTTON_MODIFY               312
#define IDC_BUTTON_GOURL                313
#define IDC_BUTTON_REALUP               314
#define IDC_EDIT_MSG                    315
#define IDC_COMBO_LIST                  316
#define IDR_PANE_CONTROL                318
#define IDR_PANE_INPUT                  319
#define IDC_TREE_INPUT                  320
#define IDC_TREE_DRAWING                321
#define IDC_DLGOCC_COMBO_REBAR_CREATEKIND 322
#define IDC_GRID_STM_EXPORT             323
#define IDC_BTN_ARCCORNER               324
#define IDC_BTN_BRACKET                 325
#define IDC_BTN_FOOTING                 326
#define IDC_BTN_FOOTING_MID             327
#define IDD_DIALOG_EXPORT_STX_OPTION    328
#define IDC_BTN_CHECK_ALL               329
#define IDC_BTN_UNCHECK_ALL             330
#define IDB_SPLASH_LSD                  330
#define IDC_BTN_EXPORT                  331
#define ID_APP_HELP1                    592
#define ID_APP_HELP2                    593
#define ID_APP_HELP3                    594
#define ID_APP_HELP4                    595
#define ID_APP_HELP5                    596
#define ID_APP_HELP_PRO                 597
#define ID_APP_HELP_PRO1                598
#define ID_APP_HELP_PRO2                599
#define ID_APP_HELP_ARCBRIDGE           600
#define ID_APP_HELP_ARCBRIDGE1          601
#define ID_TOOL_HGEXPORT                603
#define ID_BUTTON605                    605
#define ID_608                          608
#define ID_EXPORT_ASTRUTTIE             609
#define IDC_PROGRESS                    1136
#define IDC_DOM                         1342
#define ID_BASE1                        20771
#define ID_BASE2                        20772
#define ID_BASE3                        20773
#define ID_BASE4                        20774
#define ID_BASE5                        20775
#define ID_BASE6                        20776
#define ID_BASE7                        20777
#define ID_BASE8                        20778
#define ID_BASE9                        20779
#define ID_GENERAL1                     20780
#define ID_GENERAL2                     20781
#define ID_GENERAL3                     20782
#define ID_GENERAL4                     20783
#define ID_GENERAL5                     20784
#define ID_GENERAL6                     20785
#define ID_GENERAL7                     20786
#define ID_GENERAL8                     20787
#define ID_GENERAL9                     20788
#define ID_GENERAL10                    20789
#define ID_GENERAL11                    20790
#define ID_GENERAL12                    20791
#define ID_GENERAL13                    20792
#define ID_GENERAL14                    20793
#define ID_REBAR1                       20794
#define ID_REBAR2                       20795
#define ID_REBAR3                       20796
#define ID_REBAR4                       20797
#define ID_REBAR5                       20798
#define ID_REBAR6                       20799
#define ID_REBAR7                       20800
#define ID_REBAR8                       20801
#define ID_REBAR9                       20802
#define ID_REBAR10                      20803
#define ID_STM1                         20804
#define ID_STM2                         20805
#define ID_STM3                         20806
#define ID_STM4                         20807
#define ID_STM5                         20808
#define ID_32771                        32771
#define ID_SHORTCUT_START               61448
#define ID_SHORTCUT_INPUT               61449
#define ID_SHORTCUT_DRAWING             61450
#define ID_SHORTCUT_BM                  61451
#define ID_TASKGROUP_FILEOPEN           61452
#define ID_TASKGROUP_FILENEW            61453
#define ID_TASKGROUP_SUPPORT            61454
#define ID_TASKGROUP_VERSION_INFO       61455
#define ID_TASKITEM_FILEETC             61456
#define ID_TASKITEM_FILENEW             61457
#define ID_TASKITEM_HOME                61458
#define ID_TASKITEM_QNA                 61459
#define ID_TASKITEM_UPDATE              61460
#define ID_INDICATOR_PRJ                61462
#define ID_INDICATOR_ENG                61463
#define ID_INDICATOR_UNIT               61464
#define ID_INDICATOR_DIR                61465
#define ID_SHORTCUT_MODEL               61466
#define ID_INPUT_END					88888

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         610
#define _APS_NEXT_CONTROL_VALUE         325
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
